### ISSUE TITLE
Comparison with other libraries

### ISSUE THREAD

**Issue by Venryx** [SchoofsKelvin/ip-matching#3]
It would be nice if there were a comparison with some of the other ip-mask libraries.

For example:
* https://github.com/beaugunderson/ip-address
* https://github.com/indutny/node-ip
* https://github.com/rs/node-netmask

At first glance, I do like the API of this one better I think, but a comparison would help visitors decide more easily.

**Comment by SchoofsKelvin** [comment]
I'll look into those (and similar) libraries and add a section to the README.

**Comment by SchoofsKelvin** [comment]
Added the comparison (240ddc9), although it'll take a while before it gets published. Don't have any bug fixes or finished features queued up.

**Comment by Venryx** [comment]
Very detailed and useful comparison, thanks!
